from . import course_master
from . import institute
from . import survey
from . import batches
from . import examiner
from . import student
from . import exam_center
from . import invoice
from . import exam_schedule
from .marksheets import mek
from .marksheets import gsk